//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RircApps.Areas.PSP.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcePartialHTML {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcePartialHTML() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RircApps.Areas.PSP.Resources.ResourcePartialHTML", typeof(ResourcePartialHTML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Блок для формы &quot;Добавление новой записи &quot;кем выдан&quot;&quot; --&gt;
        ///&lt;div id=&quot;add_ovd_string&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;ol class=&quot;breadcrumb&quot;&gt;
        ///            &lt;li&gt;&lt;a href=&quot;/PSP/Home/Index&quot;&gt;Главное меню&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li class=&quot;active&quot;&gt;Добавление новой записи &quot;кем выдан&quot;&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;div class=&quot;page-header&quot;&gt;
        ///            &lt;h4&gt;Администрирование: &quot;Добавление новой записи &quot;кем выдан&quot;&quot;&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;panel panel-default&quot;&gt;
        ///            &lt;div class=&quot;panel-body [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string add_ovd {
            get {
                return ResourceManager.GetString("add_ovd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Блок для отчёта &quot;Все прибывшие военнообязанные за период&quot; --&gt;
        ///&lt;div id=&quot;report_arrived_military&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;ol class=&quot;breadcrumb&quot;&gt;
        ///            &lt;li&gt;&lt;a href=&quot;/PSP/Home/Index&quot;&gt;Главное меню&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li class=&quot;active&quot;&gt;Все прибывшие военнообязанные за период&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;div class=&quot;page-header&quot;&gt;
        ///            &lt;h4&gt;Отчёт: &quot;Все прибывшие военнообязанные за период&quot;&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;panel panel-default&quot;&gt;
        ///            &lt;div class=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string arrived_military_report {
            get {
                return ResourceManager.GetString("arrived_military_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Блок для формы &quot;Изменение номера помещения&quot;&quot; --&gt;
        ///&lt;div id=&quot;change_flat_num&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;ol class=&quot;breadcrumb&quot;&gt;
        ///            &lt;li&gt;&lt;a href=&quot;/PSP/Home/Index&quot;&gt;Главное меню&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li class=&quot;active&quot;&gt;Изменение номера помещения&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;div class=&quot;page-header&quot;&gt;
        ///            &lt;h4&gt;Администрирование: &quot;Изменение номера помещения&quot;&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;panel panel-default&quot;&gt;
        ///            &lt;div class=&quot;panel-body&quot;&gt;
        ///                &lt;div  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string change_flat {
            get {
                return ResourceManager.GetString("change_flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Блок для формы &quot;Удаление регистрации человека&quot;&quot; --&gt;
        ///&lt;div id=&quot;del_kart&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;ol class=&quot;breadcrumb&quot;&gt;
        ///            &lt;li&gt;&lt;a href=&quot;/PSP/Home/Index&quot;&gt;Главное меню&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li class=&quot;active&quot;&gt;Удаление карточки&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;div class=&quot;page-header&quot;&gt;
        ///            &lt;h4&gt;Администрирование: &quot;Удаление карточки&quot;&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;panel panel-default&quot;&gt;
        ///            &lt;div class=&quot;panel-body&quot;&gt;
        ///                &lt;div class=&quot;row&quot;&gt;
        ///         [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string del_kart {
            get {
                return ResourceManager.GetString("del_kart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Блок для формы &quot;Удаление регистрации человека&quot;&quot; --&gt;
        ///&lt;div id=&quot;del_person_registration&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;ol class=&quot;breadcrumb&quot;&gt;
        ///            &lt;li&gt;&lt;a href=&quot;/PSP/Home/Index&quot;&gt;Главное меню&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li class=&quot;active&quot;&gt;Удаление человека из карточки&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;div class=&quot;page-header&quot;&gt;
        ///            &lt;h4&gt;Администрирование: &quot;Удаление человека из карточки&quot;&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;panel panel-default&quot;&gt;
        ///            &lt;div class=&quot;panel-body&quot;&gt;
        ///     [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string del_person_registration {
            get {
                return ResourceManager.GetString("del_person_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Блок для отчёта &quot;Все выбывшие военнообязанные за период&quot; --&gt;
        ///&lt;div id=&quot;report_drop_out_military&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;ol class=&quot;breadcrumb&quot;&gt;
        ///            &lt;li&gt;&lt;a href=&quot;/PSP/Home/Index&quot;&gt;Главное меню&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li class=&quot;active&quot;&gt;Все выбывшие военнообязанные за период&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;div class=&quot;page-header&quot;&gt;
        ///            &lt;h4&gt;Отчёт: &quot;Все выбывшие военнообязанные за период&quot;&lt;/h4&gt;&lt;/div&gt;
        ///        &lt;div class=&quot;panel panel-default&quot;&gt;
        ///            &lt;div class=&quot;panel-body&quot;&gt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string drop_out_military_report {
            get {
                return ResourceManager.GetString("drop_out_military_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Блок для отчёта &quot;Все выписанные за период&quot; --&gt;
        ///&lt;div id=&quot;report_strength_change&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;ol class=&quot;breadcrumb&quot;&gt;
        ///            &lt;li&gt;&lt;a href=&quot;/PSP/Home/Index&quot;&gt;Главное меню&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li class=&quot;active&quot;&gt;Изменение численного состава жильцов&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;div class=&quot;page-header&quot;&gt;
        ///            &lt;h4&gt;Отчёт: &quot;Изменение численного состава жильцов&quot;&lt;/h4&gt;
        ///        &lt;/div&gt;
        ///        &lt;div class=&quot;panel panel-default&quot;&gt;
        ///            &lt;div class=&quot;panel-body&quot;&gt;
        ///         [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string strenght_change_report {
            get {
                return ResourceManager.GetString("strenght_change_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!-- Блок для отчёта &quot;Все выписанные за период&quot; --&gt;
        ///&lt;div id=&quot;report_write_out&quot;&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;ol class=&quot;breadcrumb&quot;&gt;
        ///            &lt;li&gt;&lt;a href=&quot;/PSP/Home/Index&quot;&gt;Главное меню&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li class=&quot;active&quot;&gt;Все выписанные за период&lt;/li&gt;
        ///        &lt;/ol&gt;
        ///        &lt;div class=&quot;page-header&quot;&gt;
        ///            &lt;h4&gt;Отчёт: &quot;Все выписанные за период&quot;&lt;/h4&gt;&lt;/div&gt;
        ///        &lt;div class=&quot;panel panel-default&quot;&gt;
        ///            &lt;div class=&quot;panel-body&quot;&gt;
        ///                &lt;form role=&quot;form&quot;&gt;
        ///             [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string write_out_report {
            get {
                return ResourceManager.GetString("write_out_report", resourceCulture);
            }
        }
    }
}
